// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentBridge.Infrastructure.Persistence;

#nullable disable

namespace RentBridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916174650_EscrowPayoutGuardRails")]
    partial class EscrowPayoutGuardRails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.KycVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("kyc_verifications", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedLawyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IdentityGatePassed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InspectionGatePassed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LandlordPayoutRecipientCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("landlord_payout_recipient_code");

                    b.Property<Guid>("LandlordUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LegalGatePassed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LandlordUserId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TenantUserId");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("LegalFeeRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("legal_fee_rate");

                    b.Property<decimal>("PlatformCommissionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_commission_rate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("platform_settings", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VerificationLawyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsVerified");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IdentityVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("KycVerificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.KycVerification", b =>
                {
                    b.OwnsOne("RentBridge.Domain.ValueObjects.NinNumber", "Nin", b1 =>
                        {
                            b1.Property<Guid>("KycVerificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("nin");

                            b1.HasKey("KycVerificationId");

                            b1.ToTable("kyc_verifications");

                            b1.WithOwner()
                                .HasForeignKey("KycVerificationId");
                        });

                    b.OwnsOne("RentBridge.Domain.ValueObjects.VerificationResult", "Outcome", b1 =>
                        {
                            b1.Property<Guid>("KycVerificationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("outcome_completed_at");

                            b1.Property<bool>("Outcome")
                                .HasColumnType("boolean")
                                .HasColumnName("outcome_result");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("outcome_provider");

                            b1.Property<string>("ProviderRef")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("outcome_provider_ref");

                            b1.HasKey("KycVerificationId");

                            b1.ToTable("kyc_verifications");

                            b1.WithOwner()
                                .HasForeignKey("KycVerificationId");
                        });

                    b.Navigation("Nin")
                        .IsRequired();

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Lease", b =>
                {
                    b.OwnsOne("RentBridge.Domain.Aggregates.Agreement", "Agreement", b1 =>
                        {
                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CertifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("agreement_certified_at");

                            b1.Property<Guid?>("CertifyingLawyerId")
                                .HasColumnType("uuid")
                                .HasColumnName("agreement_certifying_lawyer_id");

                            b1.Property<string>("ContentHash")
                                .HasColumnType("text")
                                .HasColumnName("agreement_content_hash");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("LeaseId");

                            b1.ToTable("leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");

                            b1.OwnsOne("RentBridge.Domain.Aggregates.AgreementDocument", "Document", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("AgreementId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ContentHash")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("content_hash");

                                    b2.Property<DateTimeOffset>("DraftedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("drafted_at");

                                    b2.Property<string>("TermsJson")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("terms_json");

                                    b2.Property<int>("Version")
                                        .HasColumnType("integer")
                                        .HasColumnName("version");

                                    b2.HasKey("Id");

                                    b2.HasIndex("AgreementId")
                                        .IsUnique();

                                    b2.ToTable("agreement_documents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AgreementId");
                                });

                            b1.OwnsMany("RentBridge.Domain.ValueObjects.SignatureRecord", "Signatures", b2 =>
                                {
                                    b2.Property<Guid>("AgreementId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ImageHash")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("image_hash");

                                    b2.Property<string>("IpAddress")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ip_address");

                                    b2.Property<string>("Party")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<DateTimeOffset>("SignedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("signed_at");

                                    b2.HasKey("AgreementId", "Id");

                                    b2.ToTable("agreement_signatures", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AgreementId");
                                });

                            b1.Navigation("Document");

                            b1.Navigation("Signatures");
                        });

                    b.OwnsMany("RentBridge.Domain.Entities.EscrowPayment", "EscrowPayments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("CheckoutUrl")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("IdempotencyKey")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PayoutAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("payout_attempts");

                            b1.Property<string>("PayoutReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("payout_reference");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("LeaseId")
                                .IsUnique()
                                .HasDatabaseName("ux_escrow_payments_lease_active_payout")
                                .HasFilter("\"Status\" IN ('Releasing', 'Released')");

                            b1.HasIndex("Reference")
                                .IsUnique();

                            b1.HasIndex("UserId", "IdempotencyKey")
                                .IsUnique();

                            b1.ToTable("escrow_payments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");

                            b1.OwnsOne("RentBridge.Domain.ValueObjects.Money", "GrossAmount", b2 =>
                                {
                                    b2.Property<Guid>("EscrowPaymentId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("gross_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("gross_currency");

                                    b2.HasKey("EscrowPaymentId");

                                    b2.ToTable("escrow_payments");

                                    b2.WithOwner()
                                        .HasForeignKey("EscrowPaymentId");
                                });

                            b1.OwnsOne("RentBridge.Domain.ValueObjects.FeeSplit", "Split", b2 =>
                                {
                                    b2.Property<Guid>("EscrowPaymentId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("EscrowPaymentId");

                                    b2.ToTable("escrow_payments");

                                    b2.WithOwner()
                                        .HasForeignKey("EscrowPaymentId");

                                    b2.OwnsOne("RentBridge.Domain.ValueObjects.Money", "LandlordPayout", b3 =>
                                        {
                                            b3.Property<Guid>("FeeSplitEscrowPaymentId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("landlord_payout");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("landlord_payout_currency");

                                            b3.HasKey("FeeSplitEscrowPaymentId");

                                            b3.ToTable("escrow_payments");

                                            b3.WithOwner()
                                                .HasForeignKey("FeeSplitEscrowPaymentId");
                                        });

                                    b2.OwnsOne("RentBridge.Domain.ValueObjects.Money", "LegalFeeShare", b3 =>
                                        {
                                            b3.Property<Guid>("FeeSplitEscrowPaymentId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("legal_fee_share");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("legal_fee_share_currency");

                                            b3.HasKey("FeeSplitEscrowPaymentId");

                                            b3.ToTable("escrow_payments");

                                            b3.WithOwner()
                                                .HasForeignKey("FeeSplitEscrowPaymentId");
                                        });

                                    b2.OwnsOne("RentBridge.Domain.ValueObjects.Money", "PlatformCommission", b3 =>
                                        {
                                            b3.Property<Guid>("FeeSplitEscrowPaymentId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("platform_commission");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("platform_commission_currency");

                                            b3.HasKey("FeeSplitEscrowPaymentId");

                                            b3.ToTable("escrow_payments");

                                            b3.WithOwner()
                                                .HasForeignKey("FeeSplitEscrowPaymentId");
                                        });

                                    b2.Navigation("LandlordPayout")
                                        .IsRequired();

                                    b2.Navigation("LegalFeeShare")
                                        .IsRequired();

                                    b2.Navigation("PlatformCommission")
                                        .IsRequired();
                                });

                            b1.Navigation("GrossAmount")
                                .IsRequired();

                            b1.Navigation("Split")
                                .IsRequired();
                        });

                    b.OwnsMany("RentBridge.Domain.Entities.InspectionRequest", "InspectionRequests", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("PreferredDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("ProposedDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RescheduleNote")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("ScheduledDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<Guid>("TenantUserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("LeaseId");

                            b1.HasIndex("TenantUserId");

                            b1.ToTable("inspection_requests", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");
                        });

                    b.Navigation("Agreement")
                        .IsRequired();

                    b.Navigation("EscrowPayments");

                    b.Navigation("InspectionRequests");
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Listing", b =>
                {
                    b.OwnsOne("RentBridge.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.Property", b =>
                {
                    b.OwnsMany("RentBridge.Domain.Entities.OwnershipDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyId");

                            b1.ToTable("ownership_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("RentBridge.Domain.ValueObjects.Address", "PropertyAddress", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("area");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Documents");

                    b.Navigation("PropertyAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("RentBridge.Domain.Aggregates.User", b =>
                {
                    b.OwnsOne("RentBridge.Domain.Entities.LawyerProfile", "LawyerProfile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BarNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("bar_number");

                            b1.Property<DateTimeOffset?>("LastAssignedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("lawyer_status");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("RentBridge.Domain.Entities.PayoutAccount", "PayoutAccount", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("payout_account_name");

                            b1.Property<string>("AccountNumberLast4")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("payout_account_last4");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("payout_bank_code");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("payout_bank_name");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("payout_account_active");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("payout_provider");

                            b1.Property<string>("RecipientCode")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("payout_recipient_code");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("payout_account_verified_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("RentBridge.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("RentBridge.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LawyerProfile");

                    b.Navigation("PayoutAccount");

                    b.Navigation("Phone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
